lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/nf-core-stableexpression_logo_light.png
    - docs/images/nf-core-stableexpression_logo_light.png
    - docs/images/nf-core-stableexpression_logo_dark.png
    - .github/PULL_REQUEST_TEMPLATE.md
  nextflow_config:
    - params.input
  template_strings:
    - tests/test_data/genorm/compute_m_measure/input/std.0.0.parquet
    - tests/test_data/genorm/compute_m_measure/input/std.1.2.parquet
    - tests/test_data/genorm/compute_m_measure/input/std.1.2.parquet

nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Olivier Coen
  description: This pipeline is dedicated to identifying the most stable genes within a single or multiple expression dataset(s). This is particularly useful for identifying the most suitable RT-qPCR reference genes for a specific species.
  force: false
  is_nfcore: true
  name: stableexpression
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0
