nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Olivier Coen
  description: This pipeline is dedicated to finding the most stable genes across
    count datasets
  force: false
  is_nfcore: true
  name: stableexpression
  org: nf-core
  outdir: .
  version: 1.0dev
