repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2
        exclude: galaxy/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff
        files: \.py$
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        files: \.py$
