#!/usr/bin/env bash

galaxy_dir="$(dirname $(readlink -f "$0"))"
tool_file="${galaxy_dir}/tool/nf_core_stableexpression.xml"

TEST_OUTDIR="test_ouptut"


ARGS="$@"

# add --update_test_data to create output file
planemo test \
    $tool_file \
    --job_output_files $TEST_OUTDIR \
    $ARGS
