#!/usr/bin/env bash
ARGS="$@"

GALAXY_DIR="$(dirname $(readlink -f "$0"))"
TOOL_FOLDER="${GALAXY_DIR}/tool_shed/tool"
TOOL_FILE="${TOOL_FOLDER}/nf_core_stableexpression.xml"

TEST_OUTDIR="tests/output"

# add --update_test_data to create output file
planemo test \
    $TOOL_FILE \
    --job_output_files $TEST_OUTDIR \
    --test_data $TOOL_FOLDER
    $ARGS
