#!/usr/bin/env bash

act_folder=$(dirname "$(realpath $0)")
root_folder=$(dirname $(dirname "${act_folder}"))

#########################################
# Parse arguments
#########################################

args=""
profile=""
while [[ $# -gt 0 ]]; do
  if [[ "$1" == "--profile" ]]; then
    profile="$2"
    shift 2
  else
    args="${args} $1" # append the string to args
    shift
  fi
done

echo "Running with args: ${args} and profile(s): ${profile}"

#########################################
# Run act
#########################################

act push \
    --job nf-test \
    --directory "${root_folder}" \
    --env-file "${act_folder}/params.env" \
    --env ARGS="${args}" \
    --env PROFILE="${profile}" \
    --workflows "${act_folder}/nf-test.yml" \
    --platform local=catthehacker/ubuntu:act-24.04 \
    --container-architecture linux/amd64 \
    --container-options "--privileged"
