name: Run nf-test
on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NFT_VER: "0.9.3"
  NFT_WORKDIR: "~"
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

jobs:
  nf-test:
    name: nf-test
    runs-on: local
    env:
      NXF_ANSI_LOG: false

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Run nf-test
        id: run_nf_test
        uses: ./act/actions/nf-test
        continue-on-error: ${{ matrix.NXF_VER == 'latest-everything' }}
        env:
          NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
          NXF_VERSION: ${{ env.NXF_VER }}
        with:
          profile: ${{ env.PROFILE }}
          tags: ${{ env.TAGS }}

      - name: Report test status
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
            echo "::error::Test with ${{ env.NXF_VER }} failed"
            # Add to workflow summary
            echo "## ❌ Test failed: ${{ env.PROFILE }} | ${{ env.NXF_VER }}" >> $GITHUB_STEP_SUMMARY
            if [[ "${{ env.NXF_VER }}" == "latest-everything" ]]; then
              echo "::warning::Test with latest-everything failed but will not cause workflow failure. Please check if the error is expected or if it needs fixing."
            fi
            if [[ "${{ env.NXF_VER }}" != "latest-everything" ]]; then
              exit 1
            fi
          fi
