#!/usr/bin/env bash

act pull_request \
    -j nf-test \
    -s GITHUB_TOKEN="$(gh auth token)" \
    --env-file ./act/params.env \
    -W ./act/nf-test.yml \
    -P local=catthehacker/ubuntu:act-24.04 \
    --container-architecture linux/amd64 \
    --container-options "--privileged"
