---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.13.7
  - conda-forge::polars==1.35.2
  - conda-forge::tqdm==4.67.1
  - conda-forge::numpy==2.3.5
  - conda-forge::numba==0.62.1
